### ISSUE TITLE
help 

### ISSUE THREAD

**Issue by End9w91091** [Cinnamonsroll/expressbots#2]
help

**Comment by Cinnamonsroll** [comment]
With?

**Comment by End9w91091** [comment]
(node:2697) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'short' of undefined
at /app/src/server/routers/bots.js:145:39
    at processTicksAndRejections (internal/process/task_queues.js:88:5)
(node:2697) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2697) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.


me sale este error a editar un bot pls help

**Comment by Cinnamonsroll** [comment]
Can you send the code which errors thaf

**Comment by End9w91091** [comment]
router.post("/:id/edit", checkAuth, async (req, res) => {
    let id = req.params.id;
    let bot2 = await model.findOne({ bot: id });
    if (!bot2) return res.redirect("/");
    if (!bot2.owners.includes(req.user.id)) return res.redirect("/");
    let data = req.body;
    let guild = client.guilds.cache.get(client.config.guilds.main);
    let user = req.user;
    let bot = (await client.users.fetch(id)) || null;
    bot2.prefix = data.prefix;
    bot2.website = data.website;
    bot2.invite = data.invite;
    bot2.github = data.github;
    bot2.desc = data.description.long;
    bot2.shortDesc = data.description.short;
    bot2.support = data.support;
    bot2.lib = data.libary;
    bot2.tags = data.tags;
    await bot2.save().then(async () => {
      res.status(201).json({ message: "Edited the bot", code: "OK" });
      let logs = guild.channels.cache.get(client.config.channels.logs);
      logs.send(
        `<@${user.id}> edited **${bot.username}#${bot.discriminator}**`
      );
    });
  });

Short y desc me da error

**Comment by Cinnamonsroll** [comment]
That's odd because data.description.long works perfectly

**Comment by End9w91091** [comment]
ami me manda ese error nose porque

**Comment by Cinnamonsroll** [comment]
In lines above like one line before let user put
console.log(data) and send what it logs

**Comment by End9w91091** [comment]
ok

**Comment by End9w91091** [comment]
pero lo pongo abajo de todo

**Comment by End9w91091** [comment]
sigue igual pero ahora me anda otro error


at /app/src/server/routers/bots.js:153:34
    at processTicksAndRejections (internal/process/task_queues.js:88:5)
(node:4373) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:4373) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by End9w91091** [comment]
sigue dándome error

**Comment by End9w91091** [comment]
Gracias por ayudarme
